name: book-app-workflow
version: 1
description: Default OpenSpec workflow - proposal → specs → design → tasks
artifacts:
  - id: proposal
    generates: proposal.md
    description: Initial proposal document outlining the change
    template: proposal.md
    instruction: >
      Create the proposal document that establishes WHY this change is needed.
      Sections:
      - **Why**: 1-2 sentences on the problem or opportunity. What problem does
      this solve? Why now?

      - **What Changes**: Bullet list of changes. Be specific about new
      capabilities, modifications, or removals. Mark breaking changes with
      **BREAKING**.

      - **Capabilities**: Identify which specs will be created or modified:
        - **New Capabilities**: List capabilities being introduced. Each becomes
          a new `specs/<name>/spec.md`. Use kebab-case names (e.g., `user-auth`,
          `data-export`).
        - **Modified Capabilities**: List existing capabilities whose
          REQUIREMENTS are changing. Only include if spec-level behavior changes
          (not just implementation details). Each needs a delta spec file. Check
          `openspec/specs/` for existing spec names. Leave empty if no
          requirement changes.
      - **Impact**: Affected code, APIs, dependencies, or systems.

      IMPORTANT: The Capabilities section is critical. It creates the contract
      between proposal and specs phases. Research existing specs before filling
      this in. Each capability listed here will need a corresponding spec file.

      Keep it concise (1-2 pages). Focus on the "why" not the "how" -
      implementation details belong in design.md.

      This is the foundation - specs, design, and tasks all build on this.
    requires: []
  - id: specs
    generates: specs/**/*.md
    description: Detailed specifications for the change
    template: spec.md
    instruction: >
      Create specification files that define WHAT the system should do.

      Create one spec file per capability listed in the proposal's Capabilities
      section.

      - New capabilities: use the exact kebab-case name from the proposal
      (specs/<capability>/spec.md).

      - Modified capabilities: use the existing spec folder name from
      openspec/specs/<capability>/ when creating the delta spec at
      specs/<capability>/spec.md.


      Delta operations (use ## headers):
      - **ADDED Requirements**: New capabilities

      - **MODIFIED Requirements**: Changed behavior - MUST include full updated
      content

      - **REMOVED Requirements**: Deprecated features - MUST include **Reason**
      and **Migration**

      - **RENAMED Requirements**: Name changes only - use FROM:/TO: format

      Format requirements:
      - Each requirement: `### Requirement: <name>` followed by description

      - Use SHALL/MUST for normative requirements (avoid should/may)

      - Each scenario: `#### Scenario: <name>` with WHEN/THEN format

      - **CRITICAL**: Scenarios MUST use exactly 4 hashtags (`####`). Using 3
      hashtags or bullets will fail silently.

      - Every requirement MUST have at least one scenario.

      MODIFIED requirements workflow:

      1. Locate the existing requirement in openspec/specs/<capability>/spec.md
      2. Copy the ENTIRE requirement block (from `### Requirement:` through all
      scenarios)
      3. Paste under `## MODIFIED Requirements` and edit to reflect new behavior
      4. Ensure header text matches exactly (whitespace-insensitive)

      Common pitfall: Using MODIFIED with partial content loses detail at
      archive time.

      If adding new concerns without changing existing behavior, use ADDED
      instead.

      Example:
      ```
      ## ADDED Requirements
      ### Requirement: User can export data
      The system SHALL allow users to export their data in CSV format.

      #### Scenario: Successful export
      - **WHEN** user clicks "Export" button
      - **THEN** system downloads a CSV file with all user data

      ## REMOVED Requirements
      ### Requirement: Legacy export
      **Reason**: Replaced by new export system
      **Migration**: Use new export endpoint at /api/v2/export

      ```

      Specs should be testable - each scenario is a potential test case.
    requires:
      - proposal
  - id: design
    generates: design.md
    description: Technical design document with implementation details
    template: design.md
    instruction: >
      Create the design document that explains HOW to implement the change.
      When to include design.md (create only if any apply):

      - Cross-cutting change (multiple services/modules) or new architectural
      pattern
      - New external dependency or significant data model changes
      - Security, performance, or migration complexity
      - Ambiguity that benefits from technical decisions before coding

      Sections:
      - **Context**: Background, current state, constraints, stakeholders
      - **Goals / Non-Goals**: What this design achieves and explicitly excludes
      - **Decisions**: Key technical choices with rationale (why X over Y?).
      Include alternatives considered for each decision.
      - **Risks / Trade-offs**: Known limitations, things that could go wrong.
      Format: [Risk] → Mitigation
      - **Migration Plan**: Steps to deploy, rollback strategy (if applicable)
      - **Open Questions**: Outstanding decisions or unknowns to resolve

      Focus on architecture and approach, not line-by-line implementation.
      Reference the proposal for motivation and specs for requirements.

      Good design docs explain the "why" behind technical decisions.
    requires:
      - proposal
  - id: tasks
    generates: tasks.md
    description: Implementation checklist with trackable tasks
    template: tasks.md
    instruction: >
      Create the task list that breaks down the implementation work.

      **IMPORTANT: Follow the template below exactly.** The apply phase parses

      checkbox format to track progress. Tasks not using `- [ ]` won't be
      tracked.


      Guidelines:
      - Do NOT include a ## 0. Git Setup group. Under TBD (ADR 0007), each
        task group gets its own branch and worktree created at the start of
        that group. Git setup is embedded in every group's X.0 task.
      - Group tasks under ## numbered headings starting at ## 1.
      - ALWAYS make the FIRST two tasks in every group the TBD git setup:
          - [ ] X.0 Run `git fetch origin` and create branch + worktree from origin/main:
                  `git worktree add ../OpenSpec-<change-name>-phase-<N> -b <change-name>/phase-<N>-<group> origin/main`
                  then `cd ../OpenSpec-<change-name>-phase-<N>`
          - [ ] X.1 Run pwd to confirm you are in ../OpenSpec-<change-name>-phase-<N>; cd into it if not
      - Replace <change-name>, <N>, and <group> with actual values for each group.
      - Renumber remaining tasks starting at X.2 onwards.
      - ALWAYS add `- [ ] X.R Reviewer sign-off` as the FINAL task in every
        group (where R is the next number after the last task in that group).
        This triggers the review loop described below. After the reviewer
        approves, the human merges the branch to main before the next group
        begins.
      - Each task MUST be a checkbox: `- [ ] X.Y Task description`
      - Tasks should be small enough to complete in one session
      - Order tasks by dependency (what must be done first?)

      Review loop (mandatory at the end of every task group): - After
      completing all other tasks in a group, launch a sub-agent using
      the Reviewer persona defined in `personas/reviewer.md`. -
      Instruct the sub-agent to review only the work done in that
      group (not the entire change). - The sub-agent writes its
      findings to a draft file named
      `openspec/changes/<change-name>/Review-phase<N>-<group-name>.md`
      (e.g. Review-phase1-project-scaffold.md). Use kebab-case for the
      group name derived from the ## heading. - If the reviewer raises
      [critical] or [important] issues: 1. Fix each issue. 2. Launch
      the Reviewer sub-agent again on the same group. 3. Repeat until
      the reviewer writes "## Approved" in the draft file. - Only then
      mark `- [x] X.R Reviewer sign-off` and wait for human to merge
      to main before moving to the next group. - [nice-to-have] issues
      do not block sign-off but MUST be recorded in the review draft.

      Example:

      ```
      ## 0. Git Setup
      - [ ] 0.1 Run `git fetch origin` to get the latest remote state
      - [ ] 0.2 Create worktree and branch from origin/main: ...
      - [ ] 0.3 Confirm worktree is active and on the correct branch
      - [ ] 0.4 Switch into the worktree directory: `cd ../OpenSpec-my-change`

      ## 1. Setup
      - [ ] 1.0 Run pwd to confirm you are in ../OpenSpec-my-change; cd into it if not
      - [ ] 1.1 Create new module structure
      - [ ] 1.2 Add dependencies to package.json
      - [ ] 1.R Reviewer sign-off → Review-phase1-setup.md

      ## 2. Core Implementation
      - [ ] 2.0 Run pwd to confirm you are in ../OpenSpec-my-change; cd into it if not
      - [ ] 2.1 Implement data export function
      - [ ] 2.2 Add CSV formatting utilities
      - [ ] 2.R Reviewer sign-off → Review-phase2-core-implementation.md

      ```

      Reference specs for what needs to be built, design for how to build it.
      Each task should be verifiable - you know when it's done.
    requires:
      - specs
      - design
apply:
  requires:
    - tasks
  tracks: tasks.md
  instruction: |
    This project uses Trunk-Based Development (ADR 0007): one short-lived branch
    and worktree per task group, each created from origin/main at group start.

    Before starting each task group:
    1. Run `git fetch origin` to get the latest main HEAD.
    2. Create a new branch and worktree from origin/main:
         git worktree add ../OpenSpec-<change-name>-phase-<N> -b <change-name>/phase-<N>-<group> origin/main
    3. Switch into the new worktree:
         cd ../OpenSpec-<change-name>-phase-<N>
    4. All implementation work for this group MUST happen inside that worktree.
    5. Never delete branches (git branch -d/-D is forbidden).
    6. Never delete worktrees (git worktree remove is forbidden).
    7. When the Reviewer approves the group, the human merges the branch to main.
       Do not begin the next group until the merge is complete.

    Then: read context files, work through pending tasks, mark complete as you go.
    Pause after each task group and wait for user confirmation before proceeding to the next.
    Pause if you hit blockers or need clarification.
