+title: Working with OpenSpec with multiple Claude profiles
#+author: HaQadosch
#+date: [2026-02-15 Sun]
#+startup: indent
#+property: header-args :results output
* Step 1: Create the different profiles
We want to start with the following profiles:
- The requirement analyst
- The solution architect
- The developer
- The reviewer

The process is to generate the profile for each project based on the
specific needs ( tech stack, constraints, ... ) of that project.

The goal, medium term, would be to use a good architecture and tech
stack (including AI) in order to go through the Flavio's course.[fn:1]
Looking at the curriculum, the first week is about an app with a DB.

#+begin_quote
BUILD AN APP WITH A DATABASE

Build a real app that saves data from day one
PROJECT: PERSONAL DASHBOARD
WHAT YOU'LL LEARN

    Describe what you want to AI and get a working app
    Understand what a database does and why your app needs one
    Build forms that create, edit, and delete records
    Run your app locally and use it every day
#+end_quote

I'm going for a book tracking with the added extra of asking why I'm
adding this book in the todo, and what I expect from this book. This
will give an angle to start reading as it could take a while before I
start it. It also gives a theme around that book and would create a
grouping of books based on common themes.

I would like to use TanStack and SQlite, so I'm basing the profiles
based on those tech.

Maybe a *offline first*, *monorepo*, and *MFE*, could be a thing to do as
well 🤔 ?
Thinking about:
- [[https://github.com/mitchellh/vouch][Vouch]]
- [[https://ipfs.tech/][IPFS]]
- [[https://posthog.com/][Posthog]]
- A TUI as web interface[fn:2]
- A pure TUI interface[fn:3]
- Check [[https://owasp.org/Top10/2025/][OWASP]] list for security
- [[https://github.com/tigerbeetle/tigerbeetle/blob/main/docs/TIGER_STYLE.md][Tigerbeetle]] style
- local first, CRDT database
- pure SSH app

After some discussions worthy of 2 ADRs, we have the tech stack. Now I
can create the 4 personnas.
#+begin_quote
Create the four personnas, taking into account the kind of app we're
building as detailled in implementationPlan.org
#+end_quote

Changed the tech stack to the full TanStack Router; creating ADR.

Changed the tech stack to include dotenvx as well; creating ADR.

Changed the tech stack to add XState; creating ADR.
* Step 2: OpenSpec and the OPSX workflow
Let's try the new new workflow.[fn:4]

#+begin_src bash
  openspec init
#+end_src

Quick start after setup:
- ~/opsx:new~ :: Create a change
- ~/opsx:continue~ :: Next artifact
- ~/opsx:apply~ :: Implement tasks
** Create schema template in your project
The idea here is to adapt opsx to the specifics of your project.
#+begin_src bash
  openspec schema fork spec-driven <project-workflow>
  # modify the schema
  openspec schema validate <project-workflow>
#+end_src
** Apparent friction with the old set up
The 4 personas created earlier are not really compatible with the way
*opsx* works. They're quite rigid and are made to be attached to a new
*claude* session at each step. *opsx* wants to do everything in any
order during the same session.

We could inject some of the 4 personas config into the *opsx*
different configuration files.


* Footnotes
[fn:4] https://github.com/Fission-AI/OpenSpec/blob/main/docs/opsx.md
There is also the getting started that looks like a nice run through.
https://github.com/Fission-AI/OpenSpec/blob/main/docs/getting-started.md
and commands reference
https://github.com/Fission-AI/OpenSpec/blob/main/docs/commands.md

[fn:3] https://github.com/vadimdemedes/ink
[fn:2] https://frankentui.com/web_react
[fn:1] https://bootcamp.dev/
