#+title: Working with OpenSpec with multiple Claude profiles
#+author: HaQadosch
#+date: [2026-02-15 Sun]
#+startup: indent
#+property: header-args :results output
* Org mode shortcuts
- tangle :: ~org-babel-tangle~, ~C-c C-v C-t~

** Config
- ~C-c C-c~ :: Refresh local setup for that file

** Dates:
- ~C-c .~ :: active timestamps
  creates an entry in the agenda
- ~C-c !~ :: inactive timestamps
  doesn´t create an entry in the agenda
- link :: [[https://orgmode.org/orgguide.html#Timestamps][timestamps]]

** Links:
- ~C-c C-l~ :: create link
- link :: [[https://orgmode.org/orgguide.html#Hyperlinks][hyperlinks]]

** Tables
- ~C-c }~ :: display cells references
- ~C-c ?~ :: display ref for that cell
  references are =@ROW$COLUMN=
- link :: [[https://orgmode.org/manual/References.html][table references]]
- formula :: =@I..II=
  select all the rows between horizontal lines (hline) 1 and 2
  =vmean(@I..II);EN= column range mean, treats empty values as null (0)

** Whitespace
- ~M-x whitespace-mode~ :: Activates a better whitespace mode
- ~M-x auto-fill-mode~ :: Auto-fill, enforce max size limit
- ~M-q~ :: Force auto-fill on current paragraph

** Feetnotes
- ~C-c C-x f~ :: Creates a footnote, see [[https://orgmode.org/guide/Creating-Footnotes.html][guide]].
- ~C-c C-c~ :: to jump between definition and refs.

** Todos
- ~C-c C-t~ :: cycling throught the states of the todos
- ~C-u C-c C-t~ :: Log the change of status

** Clocking work
- ~C-c C-x C-i~ :: Clock in
- ~C-c C-x C-o~ :: Clock out
- ~C-c C-x C-d~ :: Display clocks

** Includes files
Start with the directive ~INCLUDE~ and the location of the file
  - ~C-c '~ :: Visit the included file
  - ~C-c &~ :: Go back to the original doc
  🟡 The included doc start at the hierarchy of the inclusion
  See [[https://orgmode.org/manual/Include-Files.html][the manual]]

** Code Block - Structure Template
- ~C-c C-,~ :: Insert structure template
See [[https://orgmode.org/manual/Structure-Templates.html][17.2 Structure Templates]]
and [[https://orgmode.org/manual/Structure-of-Code-Blocks.html][16.2 Structure of Code Blocks]]

* Emacs Shortcut
- Toggle display of quick help buffer :: ~C-h C-q~ or ~M-x cheat-sheet~

* Step 1: Create the different profiles
We want to start with the following profiles:
- The requirement analyst
- The solution architect
- The developer
- The reviewer

The process is to generate the profile for each project based on the
specific needs ( tech stack, constraints, ... ) of that project.

The goal, medium term, would be to use a good architecture and tech
stack (including AI) in order to go through the Flavio's course.[fn:1]
Looking at the curriculum, the first week is about an app with a DB.

#+begin_quote
BUILD AN APP WITH A DATABASE

Build a real app that saves data from day one
PROJECT: PERSONAL DASHBOARD
WHAT YOU'LL LEARN

    Describe what you want to AI and get a working app
    Understand what a database does and why your app needs one
    Build forms that create, edit, and delete records
    Run your app locally and use it every day
#+end_quote

I'm going for a book tracking with the added extra of asking why I'm
adding this book in the todo, and what I expect from this book. This
will give an angle to start reading as it could take a while before I
start it. It also gives a theme around that book and would create a
grouping of books based on common themes.

I would like to use TanStack and SQlite, so I'm basing the profiles
based on those tech.

Maybe a *offline first*, *monorepo*, and *MFE*, could be a thing to do as
well 🤔 ?

After some discussions worthy of 2 ADRs, we have the tech stack. Now I
can create the 4 personnas.
#+begin_quote
Create the four personnas, taking into account the kind of app we're
building as detailled in implementationPlan.org
#+end_quote

Changed the teck stack to the full TanStack Router; creating ADR.

* Footnotes

[fn:1] https://bootcamp.dev/
